//DATA ACTIONS
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_ERROR = 'DATA_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';
export const UNSUBMIT_SUCCESS = 'UNSUBMIT_SUCCESS';
export const UNSUBMIT_FAIL = 'UNSUBMIT_FAIL';

//REGISTER ACTIONS
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//USER VALIDATION
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//USER MUTATION ACTIONS
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_DELETED = 'USER_DELETED';

//LOGIN VALIDATION
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOGOUT ACTION
export const LOGOUT = 'LOGOUT';

//ALERT ACTIONS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_CURRENT_ALERT = 'REMOVE_CURRENT_ALERT';
